services:
  physical_ai_manager:
    container_name: physical_ai_manager
    image: robotis/physical-ai-manager:1.0.0
    build:
      context: ../../apps/physical_ai_manager
      dockerfile: Dockerfile
    network_mode: host
    restart: unless-stopped
  physical_ai_server:
    container_name: physical_ai_server
    image: robotis/physical-ai-server:1.0.0
    tty: true
    restart: always
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=30
      - RMW_IMPLEMENTATION=rmw_zenoh_cpp
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /dev:/dev
      - ./workspace:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /tmp/.docker.xauth:/tmp/.docker.xauth:rw
      - ../../src/physical_ai_tools:/root/ros2_ws/src/physical_ai_tools/
      - ./huggingface:/root/.cache/huggingface
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/robotis/agent_sockets/physical_ai_server:/var/run/agent
    privileged: true
