string operation              # upload, download
string status                 # Idle, Uploading, Downloading, Success, Failed
string local_path             # local path of the dataset or model
string repo_id                # repo id of the dataset or model
string message                # message of the operation
uint16 progress_current       # current progress
uint16 progress_total         # total progress
float32 progress_percentage   # percentage of the progress
