########################################
# Constants
########################################
# command
uint8 NONE = 0
uint8 START = 1
uint8 FINISH = 2

uint8 command
TrainingInfo training_info
bool resume
string resume_model_path   # only used when resume training (e.g., my_model/checkpoints/000001/pretrained_model)
---
bool success
string message
